"""02_clean: data/raw_tidy.csv -> data/clean.csv (exclusions, derived columns, outcomes, treatment indicator)

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/02_clean.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

OUTCOMES = json.loads("[{\"name\": \"toward_counterarg\", \"label\": \"Support moved toward op-ed position\", \"kind\": \"single_item\", \"columns\": [\"toward_counterarg\"], \"reverse\": [], \"scale\": [1, 7], \"construction\": \"Spending support (1-7) recoded so higher = closer to op-ed position (8-strength for pro, strength for anti).\"}, {\"name\": \"certainty\", \"label\": \"Certainty in position\", \"kind\": \"single_item\", \"columns\": [\"certainty\"], \"reverse\": [], \"scale\": [0, 100], \"construction\": \"Single item 0-100.\"}, {\"name\": \"counterarg_keyword\", \"label\": \"Recall uses op-ed keyword (opposing side)\", \"kind\": \"single_item\", \"columns\": [\"counterarg_keyword\"], \"reverse\": [], \"scale\": [0, 1], \"construction\": \"Binary keyword indicator.\"}, {\"name\": \"supportive_keyword\", \"label\": \"Recall uses op-ed keyword (own side)\", \"kind\": \"single_item\", \"columns\": [\"supportive_keyword\"], \"reverse\": [], \"scale\": [0, 1], \"construction\": \"Binary keyword indicator.\"}]")
EXCLUSIONS = ["treatment in [0, 1]"]
DERIVED = json.loads("{}")
ARM_COL = "treatment"
TREATED = ["1"]            # list of treated arm values (strings)
CONTROL = "0"
ARM_LABELS = json.loads("{\"1\": \"Op-ed + chatbot\", \"0\": \"Placebo + chatbot\"}")

def arm_str(v):
    """Canonical arm value: integral numbers (1, 1.0, "1.0") -> "1"."""
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    sv = str(v).strip()
    try:
        f = float(sv)
    except ValueError:
        return sv
    return str(int(f)) if f.is_integer() else sv

def construct(df, o):
    kind = o.get("kind", "mean_items")
    lo, hi = o.get("scale") or [None, None]
    if kind == "single_item":
        return pd.to_numeric(df[o["columns"][0]], errors="coerce")
    if kind == "mean_items":
        parts = []
        for c in o["columns"]:
            s = pd.to_numeric(df[c], errors="coerce")
            if c in (o.get("reverse") or []) and lo is not None:
                s = (lo + hi) - s
            parts.append(s)
        return pd.concat(parts, axis=1).mean(axis=1, skipna=False)
    raise SystemExit(f"outcome {o['name']} has kind={kind}; custom construction must be implemented in this script")

def main():
    df = pd.read_csv(ROOT / "data" / "raw_tidy.csv")
    n0 = len(df)
    for expr in EXCLUSIONS:
        try:
            df = df.query(expr)
        except Exception as e:
            print(f"WARNING: exclusion {expr!r} could not be applied: {e}")
    print(f"sample: {n0} -> {len(df)} after exclusions {EXCLUSIONS}")
    for col, expr in DERIVED.items():
        try:
            df[col] = df.eval(expr)
        except Exception as e:
            raise SystemExit(f"derived column {col!r} = {expr!r} could not be computed: {e}")
        print(f"derived {col} = {expr}: mean={pd.to_numeric(df[col], errors='coerce').mean():.3f}")
    if ARM_COL and ARM_COL in df.columns:
        df["arm_code"] = df[ARM_COL].map(arm_str)
        keep = [a for a in TREATED + [CONTROL] if a is not None]
        df = df[df["arm_code"].isin(keep)].copy()
        df["treat"] = df["arm_code"].isin(TREATED).astype(int)
        df["arm"] = df["arm_code"].map(lambda a: ARM_LABELS.get(a, a))
        print(f"arms: {df['arm_code'].value_counts().sort_index().to_dict()}")
    for o in OUTCOMES:
        df[o["name"]] = construct(df, o)
        print(f"outcome {o['name']}: mean={df[o['name']].mean():.3f} sd={df[o['name']].std():.3f} missing={int(df[o['name']].isna().sum())}")
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "clean.csv", index=False)
    print(f"wrote data/clean.csv: {len(df)} rows, {df.shape[1]} columns")

if __name__ == "__main__":
    main()
